# Generated by Django 5.2.11 on 2026-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_laboratorio_delete_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
