# Generated by Django 5.2.11 on 2026-03-03 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='cliente',
        ),
    ]
