# Generated by Django 5.2.11 on 2026-02-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relatorio', models.CharField(max_length=50)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('dados_json', models.JSONField()),
            ],
            options={
                'ordering': ['-data_geracao'],
            },
        ),
    ]
