# Generated by Django 5.2.11 on 2026-02-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('dentista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_protese', models.CharField(max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_entrada', models.DateField()),
                ('data_prevista_saida', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('valor_servico', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('REC', 'Recebido'), ('PROD', 'Em Produção'), ('FIN', 'Finalizado'), ('ENT', 'Entregue'), ('CAN', 'Cancelado')], default='REC', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_como_cliente', to='cliente.cliente')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='dentista.dentista')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_como_lab', to='cliente.cliente')),
            ],
            options={
                'ordering': ['-data_entrada'],
            },
        ),
    ]
