# Generated by Django 5.2.11 on 2026-02-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentista', '0001_initial'),
        ('servico', '0002_alter_servico_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='dentista.dentista'),
        ),
    ]
