# Generated by Django 5.2.11 on 2026-03-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_alter_servico_dentista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='laboratorio',
        ),
        migrations.AddField(
            model_name='servico',
            name='paciente',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
